### ISSUE TITLE
Cannot import react-router

### ISSUE THREAD

**Issue by thebarty** [asmyshlyaev177/state-in-url#14]
`import { useUrlState } from 'state-in-url/react-router'
`

leads to 
```

Uncaught Error: Cannot find module 'state-in-url/react-router'
    at makeMissingError (modules-runtime-hot.js?hash=740f2079be9cde2bf010e27ef9713c36c6491a66:232:12)
    at Module.resolve (modules-runtime-hot.js?hash=740f2079be9cde2bf010e27ef9713c36c6491a66:247:17)
    at Module.moduleLink [as link] (modules.js?hash=9dcfdf759efa47693da31a9949583b7253b6ca74:361:25)
    at app.js?hash=48fd84b88fcc541f1c7fd8175fec0e3bbfd72bcc:989:11
    at module (CallActivityTable.jsx:364:34)
    at fileEvaluate (modules-runtime-hot.js?hash=740f2079be9cde2bf010e27ef9713c36c6491a66:386:7)
    at Module.require (modules-runtime-hot.js?hash=740f2079be9cde2bf010e27ef9713c36c6491a66:268:27)
    at mod.require (modules.js?hash=9dcfdf759efa47693da31a9949583b7253b6ca74:296:33)
    at Module.moduleLink [as link] (modules.js?hash=9dcfdf759efa47693da31a9949583b7253b6ca74:368:22)
    at app.js?hash=48fd84b88fcc541f1c7fd8175fec0e3bbfd72bcc:751:11```

**Comment by asmyshlyaev177** [comment]
Hi @thebarty , tnx for reporting, I will look into it.

**Comment by asmyshlyaev177** [comment]
@thebarty Can you post what tech stack you are using?

**Comment by thebarty** [comment]
@asmyshlyaev177 thanks for responding so quickly. I am using meteor with React in frontend. Quite a standard setup: https://guide.meteor.com/react.

Latest Meteor 3.0
node version: v16.14.2
React with react-router v6
no typescript

Does this help? Do you need more info?

**Comment by asmyshlyaev177** [comment]
> @asmyshlyaev177 thanks for responding so quickly. I am using meteor with React in frontend. Quite a standard setup: https://guide.meteor.com/react.
> 
> Latest Meteor 3.0 node version: v16.14.2 React with react-router v6 no typescript
> 
> Does this help? Do you need more info?

It's helpful, something with Meteor.

Can you try to import it like this
```typescript
import stateInUrl from 'state-in-url/react-router'
...
stateInUrl.useStateInUrl({...}) 
```

**Comment by thebarty** [comment]
@asmyshlyaev177 you are superfast.

I tried out
```
import stateInUrl from 'state-in-url/react-router'
…
console.log('stateInUrl', stateInUrl)
```

and still seeing

<img width="754" alt="Meteor_App" src="https://github.com/user-attachments/assets/7e44c53e-21ab-4f17-a4b9-f359e79ae1e2">

**Comment by asmyshlyaev177** [comment]
@thebarty ok, meteor has some issues with esm modules, still not fixed 
https://github.com/meteor/meteor/discussions/11727

Seems like syntax like this should work
```typescript
// folder structure from node_modules/state-in-url
import { useUrlState } from "state-in-url/dist/react-router/useUrlState/useUrlState.mjs";
```

**Comment by asmyshlyaev177** [comment]
Also enabled `modules` and ecmascript, `meteor add modules` and  `meteor add ecmascript`

**Comment by thebarty** [comment]
@asmyshlyaev177 thanks for your support!

Seems like I got the object by using your import:
<img width="482" alt="Meteor_App" src="https://github.com/user-attachments/assets/870bf314-983f-4877-a0f4-5541798f5ed8">

Closing the ticket
