### ISSUE TITLE
Using `interface` instead of `type` to type defaultState produces TS error

### ISSUE THREAD

**Issue by nordowl** [asmyshlyaev177/state-in-url#21]
**Describe the bug**
Trying to type the `defaultState` using `interface` produces a TypeScript error (using state-in-url version 4.0.4).
```
Type 'DefaultUrlState' is not assignable to type 'JSONCompatible'.
  Index signature for type 'string' is missing in type 'DefaultUrlState'.ts(2322)
useUrlState.d.ts(27, 5): The expected type comes from property 'defaultState' which is declared here on type '{ defaultState: JSONCompatible; searchParams?: object | undefined; replace?: boolean | undefined; scroll?: boolean | undefined; useHistory?: boolean | undefined; }'
```

**To Reproduce**

```ts
interface DefaultUrlState {
    whatever: string[]
}

const defaultState: DefaultUrlState = { whatever: [] }

const { setUrl, urlState } = useUrlState({ defaultState })
```

This error can be fixed by using
```ts
type DefaultUrlState = {
    whatever: string[]
}
```

Not sure if this behavior in intended or not.

**Expected behavior**
No TypeScript error

**Comment by asmyshlyaev177** [comment]
I will look into it, I didn't expect this from TS.

**Comment by asmyshlyaev177** [comment]
@nordowl Seems like `Interface` and `Type` behave differently in TS. Is there use cases when you can't use `Type` for `defaultState` ?

**Comment by nordowl** [comment]
It's mainly a preference thing to be honest. I prefer using `interface` over `type` when working with an object.

**Comment by asmyshlyaev177** [comment]
> It's mainly a preference thing to be honest. I (and probably others?) prefer using `interface` over `type` when working with an object.

I see. Not sure if can make it work with Interface, will note about it in documentation.
