### ISSUE TITLE
Argument of type 'readonly string[]' is not assignable to parameter of type 'string[]'.

### ISSUE THREAD

**Issue by nordowl** [asmyshlyaev177/state-in-url#22]
**Describe the bug**
I want to pass an `urlState` property of type `string[]` to a function. But that produces a TS error, because `urlState` uses `readonly` properties.

**To Reproduce**
Just some pseudo code
```ts
import { useUrlState } from "state-in-url"

function assignCats(cats: string[], owner: string) {
    return
}

type DefaultUrlState = {
    cats: string[]
    owner: string
}

const defaultState: DefaultUrlState = { cats: [], owner: "" }

const { setUrl, urlState } = useUrlState({ defaultState })

assignCats(urlState.cats, urlState.owner)
```

Trying to pass `urlState.cats` as the `cats` parameter throws:
```
Argument of type 'readonly string[]' is not assignable to parameter of type 'string[]'.
  The type 'readonly string[]' is 'readonly' and cannot be assigned to the mutable type 'string[]'
```

**Expected behavior**
No errors.

**Comment by asmyshlyaev177** [comment]
@nordowl Can you post your typescript version?

**Comment by asmyshlyaev177** [comment]
@nordowl does it make sense to return regular data without `readonly`?

**Comment by nordowl** [comment]
I think having to specifying `readonly` everywhere you want to access the data is a step not needed. Especially if you then want to modify the data - e.g. you can't use `array.push()` anymore. Sure, you could use the spread operator and create a new array or what not, but that might potentially be more memory-intensive.

For now what I've done is use type casting with `as`, e.g. `myFunc(urlState.myArray as string[])`. But that's not great I think.

Having mutable array types would make things a little easier in my opinion.

**Comment by asmyshlyaev177** [comment]
@nordowl I guess it's not really needed, will remove it in a new version.

**Comment by asmyshlyaev177** [comment]
@nordowl will be released when https://github.com/asmyshlyaev177/state-in-url/actions/runs/11758298425 pass, issues closing automatically, not sure why.

**Comment by nordowl** [comment]
@asmyshlyaev177 Thanks, I appreciate it!

**Comment by asmyshlyaev177** [comment]
> @asmyshlyaev177 Thanks, I appreciate it!

It's release few minutes ago.
